### ISSUE TITLE
minimalizujemy różnice między dwoma warunkami

### ISSUE THREAD

**Issue by themeo** [MartinJurczyk/EEG-codes#1]
https://github.com/MartinJurczyk/EEG-codes/blob/0b603dd4a197cfdb4b47d90997effd808d026041/KubaCodes.py#L113

W jednym warunku eksperymentalnym jest liczba, w drugim słowo. Żeby zachować pozory podobieństwa, `0` zamieniłbym na `False`

**Comment by jakubdoman** [comment]
Poprawione.
