### ISSUE TITLE
'or'? 

### ISSUE THREAD

**Issue by themeo** [MartinJurczyk/EEG-codes#2]
https://github.com/MartinJurczyk/EEG-codes/blob/0b603dd4a197cfdb4b47d90997effd808d026041/KubaCodes.py#L118

Nie rozumiem użycia słowa 'or'? Sprawia wrażenie jakby kod miał robić coś losowego.

**Comment by themeo** [comment]
Ok, zrozumiałem. Trzeba odwrócić kolejność instrukcji. Wpierw napisać że obliczamy jedno i drugie, a potem że szukamy maksa. Inaczej jest trudne do zrozumienia.

**Comment by jakubdoman** [comment]
Poprawione w polskim opisie.
