### ISSUE TITLE
uszczegolowienie opisu

### ISSUE THREAD

**Issue by themeo** [MartinJurczyk/EEG-codes#6]
https://github.com/MartinJurczyk/EEG-codes/blob/0b603dd4a197cfdb4b47d90997effd808d026041/KubaCodes.py#L244

Doopisalbym algorytm w opisie - iterujemy przez wszystkie litery, ale pierwszym n robimy uppercase

**Comment by jakubdoman** [comment]
Dodane w polskim opisie.
