### ISSUE TITLE
kod dla list, ale używa setów... 

### ISSUE THREAD

**Issue by themeo** [MartinJurczyk/EEG-codes#7]
https://github.com/MartinJurczyk/EEG-codes/blob/0b603dd4a197cfdb4b47d90997effd808d026041/KubaCodes.py#L290

Ten kod jest napisany tak żeby działał na listach, ale niepotrzebnie wspomina o setach które oferują prostsze (inne) rozwiązanie..

**Comment by jakubdoman** [comment]
Poprawiłem funkcję. Usunąłem set.
