### ISSUE TITLE
zbyt semantycznie podobny błąd

### ISSUE THREAD

**Issue by themeo** [MartinJurczyk/EEG-codes#8]
https://github.com/MartinJurczyk/EEG-codes/blob/0b603dd4a197cfdb4b47d90997effd808d026041/KubaCodes.py#L321

To jest "poprawny" błąd ale użyłbym funkcji której powierzchowne znaczenie jest bardziej różne od poprawnej wersji. instancja i podklasa są semantycznie całkiem podobne.. a chcemy testować mechanizm mózgowy który jest wrażliwy na semantyczne podobieństwa, nawet jeśli są niepoprawne.

**Comment by jakubdoman** [comment]
Zmieniłem błąd na bardziej różniący się. Zamieniłem 'issubclass' na 'enumerate'.
