### ISSUE TITLE
nie do końca przejrzysty opis

### ISSUE THREAD

**Issue by themeo** [MartinJurczyk/EEG-codes#9]
https://github.com/MartinJurczyk/EEG-codes/blob/0b603dd4a197cfdb4b47d90997effd808d026041/KubaCodes.py#L345

Ten opis nie jest całkiem zrozumiały przy pierwszym przeczytaniu. Łatwiej zacząć:
majac listę liczb, sklej je w jednego stringa zawierającego kolejne cyfry z kolejnych liczb zawartych w liście -- albo coś w ten deseń.

**Comment by jakubdoman** [comment]
Zmieniłem opis.
